import "@/styles/globals.css";
import "@/styles/Login.css";
import "@/styles/Home.css";
import "@/styles/Profile.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Side from "@/components/Side";
import BackToHome from "@/components/BackToHome";
import ProfileButton from "@/components/ProfileButton";


export default function App({ Component, pageProps }) {
  // return <Component {...pageProps} />;



  return (
      <>
        <Head>
          <title>Iko</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/headrovot.png"/>
        </Head>
        <div className="page-layout">
            {/*(true && 8) == 8*/}
            {/*(false && 8) == false*/}
            {/*if (Component != Login) {*/}



          <Component {...pageProps} />




            {Component.name == "Login" &&
            <Side/>}
            {Component.name == "Profile" &&
                <BackToHome/>}
            {Component.name == "Home" &&
                <ProfileButton/>}

        </div>


      </>
  )


}
